// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/payment/v1/payment_service.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentStatus represents the status of a payment
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_COMPLETED   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_CANCELLED   PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 5
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_COMPLETED",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_CANCELLED",
		5: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_COMPLETED":   2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_CANCELLED":   4,
		"PAYMENT_STATUS_REFUNDED":    5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_v1_payment_service_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_proto_payment_v1_payment_service_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{0}
}

// PaymentMethod represents the method used for payment
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED    PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD    PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_DEBIT_CARD     PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_BANK_TRANSFER  PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_DIGITAL_WALLET PaymentMethod = 4
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CREDIT_CARD",
		2: "PAYMENT_METHOD_DEBIT_CARD",
		3: "PAYMENT_METHOD_BANK_TRANSFER",
		4: "PAYMENT_METHOD_DIGITAL_WALLET",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED":    0,
		"PAYMENT_METHOD_CREDIT_CARD":    1,
		"PAYMENT_METHOD_DEBIT_CARD":     2,
		"PAYMENT_METHOD_BANK_TRANSFER":  3,
		"PAYMENT_METHOD_DIGITAL_WALLET": 4,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_v1_payment_service_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_proto_payment_v1_payment_service_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{1}
}

// CreatePaymentRequest represents a request to create a payment
type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`                                   // Amount in cents
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`                                // Currency code (e.g., USD, EUR)
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // Payment method
	CustomerId    string                 `protobuf:"bytes,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`          // Customer identifier
	OrderId       string                 `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                   // Order identifier
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`                          // Payment description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreatePaymentRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CreatePaymentResponse represents a response to payment creation
type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// GetPaymentRequest represents a request to retrieve a payment
type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Payment ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetPaymentResponse represents a response with payment details
type GetPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// UpdatePaymentStatusRequest represents a request to update payment status
type UpdatePaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // Payment ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // New status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentStatusRequest) Reset() {
	*x = UpdatePaymentStatusRequest{}
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusRequest) ProtoMessage() {}

func (x *UpdatePaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePaymentStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePaymentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpdatePaymentStatusResponse represents a response to status update
type UpdatePaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentStatusResponse) Reset() {
	*x = UpdatePaymentStatusResponse{}
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusResponse) ProtoMessage() {}

func (x *UpdatePaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePaymentStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetPaymentsByCustomerRequest represents a request to get customer payments
type GetPaymentsByCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"` // Customer identifier
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                            // Maximum number of payments to return
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                          // Number of payments to skip
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsByCustomerRequest) Reset() {
	*x = GetPaymentsByCustomerRequest{}
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsByCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsByCustomerRequest) ProtoMessage() {}

func (x *GetPaymentsByCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsByCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentsByCustomerRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaymentsByCustomerRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetPaymentsByCustomerRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPaymentsByCustomerRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// GetPaymentsByCustomerResponse represents a response with customer payments
type GetPaymentsByCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsByCustomerResponse) Reset() {
	*x = GetPaymentsByCustomerResponse{}
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsByCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsByCustomerResponse) ProtoMessage() {}

func (x *GetPaymentsByCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsByCustomerResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentsByCustomerResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaymentsByCustomerResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *GetPaymentsByCustomerResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ListPaymentsRequest represents a request to list payments
type ListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`   // Maximum number of payments to return
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // Number of payments to skip
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListPaymentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPaymentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListPaymentsResponse represents a response with payments list
type ListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListPaymentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Payment represents a payment transaction
type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // Payment identifier
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                                   // Amount in cents
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`                                // Currency code
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                    // Payment status
	PaymentMethod string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // Payment method
	CustomerId    string                 `protobuf:"bytes,6,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`          // Customer identifier
	OrderId       string                 `protobuf:"bytes,7,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                   // Order identifier
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`                          // Payment description
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`             // Creation timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`            // Last update timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_service_proto_rawDescGZIP(), []int{10}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Payment) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_payment_v1_payment_service_proto protoreflect.FileDescriptor

const file_proto_payment_v1_payment_service_proto_rawDesc = "" +
	"\n" +
	"&proto/payment/v1/payment_service.proto\x12\n" +
	"payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n" +
	"\x14CreatePaymentRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vcustomer_id\x18\x04 \x01(\tR\n" +
	"customerId\x12\x19\n" +
	"\border_id\x18\x05 \x01(\tR\aorderId\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"F\n" +
	"\x15CreatePaymentResponse\x12-\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentR\apayment\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12GetPaymentResponse\x12-\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentR\apayment\"D\n" +
	"\x1aUpdatePaymentStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"7\n" +
	"\x1bUpdatePaymentStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"m\n" +
	"\x1cGetPaymentsByCustomerRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"f\n" +
	"\x1dGetPaymentsByCustomerResponse\x12/\n" +
	"\bpayments\x18\x01 \x03(\v2\x13.payment.v1.PaymentR\bpayments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"C\n" +
	"\x13ListPaymentsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"]\n" +
	"\x14ListPaymentsResponse\x12/\n" +
	"\bpayments\x18\x01 \x03(\v2\x13.payment.v1.PaymentR\bpayments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xe0\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vcustomer_id\x18\x06 \x01(\tR\n" +
	"customerId\x12\x19\n" +
	"\border_id\x18\a \x01(\tR\aorderId\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xbf\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELLED\x10\x04\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x05*\xb3\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_METHOD_DEBIT_CARD\x10\x02\x12 \n" +
	"\x1cPAYMENT_METHOD_BANK_TRANSFER\x10\x03\x12!\n" +
	"\x1dPAYMENT_METHOD_DIGITAL_WALLET\x10\x042\xdc\x03\n" +
	"\x0ePaymentService\x12T\n" +
	"\rCreatePayment\x12 .payment.v1.CreatePaymentRequest\x1a!.payment.v1.CreatePaymentResponse\x12K\n" +
	"\n" +
	"GetPayment\x12\x1d.payment.v1.GetPaymentRequest\x1a\x1e.payment.v1.GetPaymentResponse\x12f\n" +
	"\x13UpdatePaymentStatus\x12&.payment.v1.UpdatePaymentStatusRequest\x1a'.payment.v1.UpdatePaymentStatusResponse\x12l\n" +
	"\x15GetPaymentsByCustomer\x12(.payment.v1.GetPaymentsByCustomerRequest\x1a).payment.v1.GetPaymentsByCustomerResponse\x12Q\n" +
	"\fListPayments\x12\x1f.payment.v1.ListPaymentsRequest\x1a .payment.v1.ListPaymentsResponseB>Z<github.com/jia-app/paymentservice/proto/payment/v1;paymentv1b\x06proto3"

var (
	file_proto_payment_v1_payment_service_proto_rawDescOnce sync.Once
	file_proto_payment_v1_payment_service_proto_rawDescData []byte
)

func file_proto_payment_v1_payment_service_proto_rawDescGZIP() []byte {
	file_proto_payment_v1_payment_service_proto_rawDescOnce.Do(func() {
		file_proto_payment_v1_payment_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_v1_payment_service_proto_rawDesc), len(file_proto_payment_v1_payment_service_proto_rawDesc)))
	})
	return file_proto_payment_v1_payment_service_proto_rawDescData
}

var file_proto_payment_v1_payment_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_payment_v1_payment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_payment_v1_payment_service_proto_goTypes = []any{
	(PaymentStatus)(0),                    // 0: payment.v1.PaymentStatus
	(PaymentMethod)(0),                    // 1: payment.v1.PaymentMethod
	(*CreatePaymentRequest)(nil),          // 2: payment.v1.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),         // 3: payment.v1.CreatePaymentResponse
	(*GetPaymentRequest)(nil),             // 4: payment.v1.GetPaymentRequest
	(*GetPaymentResponse)(nil),            // 5: payment.v1.GetPaymentResponse
	(*UpdatePaymentStatusRequest)(nil),    // 6: payment.v1.UpdatePaymentStatusRequest
	(*UpdatePaymentStatusResponse)(nil),   // 7: payment.v1.UpdatePaymentStatusResponse
	(*GetPaymentsByCustomerRequest)(nil),  // 8: payment.v1.GetPaymentsByCustomerRequest
	(*GetPaymentsByCustomerResponse)(nil), // 9: payment.v1.GetPaymentsByCustomerResponse
	(*ListPaymentsRequest)(nil),           // 10: payment.v1.ListPaymentsRequest
	(*ListPaymentsResponse)(nil),          // 11: payment.v1.ListPaymentsResponse
	(*Payment)(nil),                       // 12: payment.v1.Payment
	(*timestamppb.Timestamp)(nil),         // 13: google.protobuf.Timestamp
}
var file_proto_payment_v1_payment_service_proto_depIdxs = []int32{
	12, // 0: payment.v1.CreatePaymentResponse.payment:type_name -> payment.v1.Payment
	12, // 1: payment.v1.GetPaymentResponse.payment:type_name -> payment.v1.Payment
	12, // 2: payment.v1.GetPaymentsByCustomerResponse.payments:type_name -> payment.v1.Payment
	12, // 3: payment.v1.ListPaymentsResponse.payments:type_name -> payment.v1.Payment
	13, // 4: payment.v1.Payment.created_at:type_name -> google.protobuf.Timestamp
	13, // 5: payment.v1.Payment.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 6: payment.v1.PaymentService.CreatePayment:input_type -> payment.v1.CreatePaymentRequest
	4,  // 7: payment.v1.PaymentService.GetPayment:input_type -> payment.v1.GetPaymentRequest
	6,  // 8: payment.v1.PaymentService.UpdatePaymentStatus:input_type -> payment.v1.UpdatePaymentStatusRequest
	8,  // 9: payment.v1.PaymentService.GetPaymentsByCustomer:input_type -> payment.v1.GetPaymentsByCustomerRequest
	10, // 10: payment.v1.PaymentService.ListPayments:input_type -> payment.v1.ListPaymentsRequest
	3,  // 11: payment.v1.PaymentService.CreatePayment:output_type -> payment.v1.CreatePaymentResponse
	5,  // 12: payment.v1.PaymentService.GetPayment:output_type -> payment.v1.GetPaymentResponse
	7,  // 13: payment.v1.PaymentService.UpdatePaymentStatus:output_type -> payment.v1.UpdatePaymentStatusResponse
	9,  // 14: payment.v1.PaymentService.GetPaymentsByCustomer:output_type -> payment.v1.GetPaymentsByCustomerResponse
	11, // 15: payment.v1.PaymentService.ListPayments:output_type -> payment.v1.ListPaymentsResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_payment_v1_payment_service_proto_init() }
func file_proto_payment_v1_payment_service_proto_init() {
	if File_proto_payment_v1_payment_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_v1_payment_service_proto_rawDesc), len(file_proto_payment_v1_payment_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_v1_payment_service_proto_goTypes,
		DependencyIndexes: file_proto_payment_v1_payment_service_proto_depIdxs,
		EnumInfos:         file_proto_payment_v1_payment_service_proto_enumTypes,
		MessageInfos:      file_proto_payment_v1_payment_service_proto_msgTypes,
	}.Build()
	File_proto_payment_v1_payment_service_proto = out.File
	file_proto_payment_v1_payment_service_proto_goTypes = nil
	file_proto_payment_v1_payment_service_proto_depIdxs = nil
}
