// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckEntitlement(ctx context.Context, arg CheckEntitlementParams) (*Entitlement, error)
	CountPayments(ctx context.Context) (int64, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (*Payment, error)
	DeletePayment(ctx context.Context, id uuid.UUID) error
	GetEntitlementByID(ctx context.Context, id uuid.UUID) (*Entitlement, error)
	GetOutboxEventByID(ctx context.Context, id uuid.UUID) (*Outbox, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (*Payment, error)
	GetPaymentByOrderID(ctx context.Context, orderID string) (*Payment, error)
	GetPaymentsByCustomerID(ctx context.Context, arg GetPaymentsByCustomerIDParams) ([]*Payment, error)
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]*Outbox, error)
	GetPlanByID(ctx context.Context, id string) (*Plan, error)
	GetWebhookEventByEventID(ctx context.Context, eventID string) (*WebhookEvent, error)
	InsertEntitlement(ctx context.Context, arg InsertEntitlementParams) (*Entitlement, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (*Outbox, error)
	InsertPlan(ctx context.Context, arg InsertPlanParams) (*Plan, error)
	InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (*WebhookEvent, error)
	ListActivePlans(ctx context.Context) ([]*Plan, error)
	ListEntitlementsByUser(ctx context.Context, userID string) ([]*Entitlement, error)
	ListExpiringEntitlements(ctx context.Context) ([]*Entitlement, error)
	ListFailedOutboxEvents(ctx context.Context, limit int32) ([]*Outbox, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]*Payment, error)
	ListUnprocessedWebhookEvents(ctx context.Context, limit int32) ([]*WebhookEvent, error)
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) (*Outbox, error)
	MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) (*Outbox, error)
	MarkWebhookEventProcessed(ctx context.Context, eventID string) (*WebhookEvent, error)
	UpdateEntitlementExpiry(ctx context.Context, arg UpdateEntitlementExpiryParams) (*Entitlement, error)
	UpdateEntitlementStatus(ctx context.Context, arg UpdateEntitlementStatusParams) (*Entitlement, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (*Payment, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (*Payment, error)
	UpdatePlanActive(ctx context.Context, arg UpdatePlanActiveParams) (*Plan, error)
}

var _ Querier = (*Queries)(nil)
