server:
  port: 50051

database:
  host: localhost
  port: 5432
  user: paymentservice
  password: paymentservice123
  dbname: paymentservice
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

log:
  level: info
