app_name: "payment-service"

grpc:
  address: ":8081"

postgres:
  dsn: "postgres://neondb_owner:sLdJyF0w2Unv@ep-wild-wave-a1nsn7ul.ap-southeast-1.aws.neon.tech:5432/jia_family_app?sslmode=require"
  max_conns: 10

redis:
  addr: "localhost:6379"
  db: 0
  password: ""

auth:
  public_key_pem: ""

billing:
  provider: "stripe"
  stripe_secret: "${STRIPE_SECRET}"
  stripe_publishable: "${STRIPE_PUBLISHABLE_KEY}"

events:
  provider: "kafka"
  brokers: ["localhost:9092"]
  topic: "payments"

log:
  level: "info"
