app_name: "${APP_NAME}"

grpc:
  address: "${GRPC_ADDRESS}"

postgres:
  dsn: "${POSTGRES_DSN}"
  max_conns: 10

redis:
  addr: "${REDIS_ADDR}"
  db: "${REDIS_DB}"
  password: "${REDIS_PASSWORD}"

auth:
  public_key_pem: "${AUTH_PUBLIC_KEY_PEM}"

billing:
  provider: "${BILLING_PROVIDER}"
  stripe_secret: "${STRIPE_SECRET}"

events:
  provider: "${EVENTS_PROVIDER}"
  brokers: "${EVENTS_BROKERS}"
  topic: "${EVENTS_TOPIC}"

log:
  level: "${LOG_LEVEL}"
