// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Entitlement struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         string           `json:"user_id"`
	FamilyID       pgtype.Text      `json:"family_id"`
	FeatureCode    string           `json:"feature_code"`
	PlanID         string           `json:"plan_id"`
	SubscriptionID pgtype.Text      `json:"subscription_id"`
	Status         string           `json:"status"`
	GrantedAt      pgtype.Timestamp `json:"granted_at"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	UsageLimits    []byte           `json:"usage_limits"`
	Metadata       []byte           `json:"metadata"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Payment struct {
	ID                pgtype.UUID      `json:"id"`
	Currency          string           `json:"currency"`
	Status            string           `json:"status"`
	PaymentMethod     string           `json:"payment_method"`
	CustomerID        string           `json:"customer_id"`
	OrderID           string           `json:"order_id"`
	Description       pgtype.Text      `json:"description"`
	ExternalPaymentID pgtype.Text      `json:"external_payment_id"`
	FailureReason     pgtype.Text      `json:"failure_reason"`
	Metadata          []byte           `json:"metadata"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	// Amount in dollars (e.g., 19.99)
	Amount pgtype.Numeric `json:"amount"`
}

type Plan struct {
	ID           string           `json:"id"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	FeatureCodes []string         `json:"feature_codes"`
	BillingCycle pgtype.Text      `json:"billing_cycle"`
	PriceCents   int32            `json:"price_cents"`
	Currency     string           `json:"currency"`
	MaxUsers     pgtype.Int4      `json:"max_users"`
	UsageLimits  []byte           `json:"usage_limits"`
	Metadata     []byte           `json:"metadata"`
	Active       bool             `json:"active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type PricingZone struct {
	ID                      pgtype.UUID        `json:"id"`
	Country                 string             `json:"country"`
	IsoCode                 string             `json:"iso_code"`
	Zone                    string             `json:"zone"`
	ZoneName                string             `json:"zone_name"`
	WorldBankClassification pgtype.Text        `json:"world_bank_classification"`
	GniPerCapitaThreshold   pgtype.Text        `json:"gni_per_capita_threshold"`
	PricingMultiplier       pgtype.Numeric     `json:"pricing_multiplier"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}
